---
# Snry Shell Uninstall Playbook

- name: Snry Shell Uninstall
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Include uninstall role
      ansible.builtin.import_role:
        name: uninstall
