# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing
exec-once=/usr/lib/pam_kwallet_init
exec-once=xrandr --output DP-1 --primary
