# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
$mainMod = SUPER
$subMod = SUPER_SHIFT
$tetMod = SUPER_CTRL

unbind = $mainMod, Super_L
unbind = $mainMod, Super_R
unbind = $mainMod, T
unbind = Ctrl+Alt, T
unbind = $mainMod, E
unbind = $mainMod, W
unbind = Ctrl+Super+Shift+Alt, W
unbind = $mainMod, X
unbind = Ctrl+Super, V
unbind = $mainMod, L
unbind = $mainMod, D

bind = $mainMod, D, global, quickshell:searchToggleRelease

bind = $tetMod, Slash, exec, xdg-open ~/.config/snry-shell/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

bindd = $mainMod, L, Lock, exec, sh -c 'touch $XDG_RUNTIME_DIR/snry-locked && hyprctl dispatch global quickshell:lock'

bind = $mainMod, Q, killactive,
bind = $subMod, Q, forcekillactive,
bind = $subMod, E, exit,
bind = $mainMod, T, exec, dolphin
bind = $mainMod, V, togglefloating,
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod, w, swapnext
bind = $mainMod, m, fullscreen, 1
bind = $subMod, m, fullscreen, 0
bind = $mainMod, f, togglefloating
bind = $mainMod, 0, workspace, 10
bind = $subMod, 0, movetoworkspace, 10

bind = $subMod, 1, movetoworkspace, 1
bind = $subMod, 2, movetoworkspace, 2
bind = $subMod, 3, movetoworkspace, 3
bind = $subMod, 4, movetoworkspace, 4
bind = $subMod, 5, movetoworkspace, 5
bind = $subMod, 6, movetoworkspace, 6
bind = $subMod, 7, movetoworkspace, 7
bind = $subMod, 8, movetoworkspace, 8
bind = $subMod, 9, movetoworkspace, 9
bind = $subMod, 0, movetoworkspace, 10
# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above
