-- Theme colors (auto-generated by switchwall.sh, do not edit manually)

hl.config({
	general = {
		col = {
			active_border = "rgba(F7DCDE39)",
			inactive_border = "rgba(A58A8D30)",
		},
	},
})

hl.config({
	misc = {
		background_color = "rgba(1D1011FF)",
	},
})

-- Plugin: hyprbars
-- NOTE: hyprbars plugin config uses its own syntax. These may need plugin-specific API.
-- For now, keep as exec commands until hyprbars supports Lua natively.

-- Pinned window border color
hl.window_rule({ match = { pin = true }, border_color = "rgba(FFB2BCAA) rgba(FFB2BC77)" })
