# Default variables
# Copy these to ~/.config/hypr/custom/variables.conf to make changes in a dotfiles-update-friendly manner

# Apps
# PULL REQUESTS ADDING MORE WILL NOT BE ACCEPTED, CONFIG FOR YOURSELF
$terminal = ~/.local/bin/snry-daemon send launch "ghostty" "foot" "alacritty" "wezterm" "konsole" "kgx" "uxterm" "xterm"
$fileManager = ~/.local/bin/snry-daemon send launch "dolphin" "nautilus" "nemo" "thunar" "ghostty -e bash -c yazi"
$browser = ~/.local/bin/snry-daemon send launch "google-chrome-stable" "zen-browser" "firefox" "brave" "chromium" "microsoft-edge-stable" "opera" "librewolf"
$codeEditor = ~/.local/bin/snry-daemon send launch "antigravity" "code" "codium" "cursor" "zed" "zedit" "zeditor" "kate" "gnome-text-editor" "emacs" "command -v nvim && ghostty -e nvim" "command -v micro && ghostty -e micro"
$officeSoftware = ~/.local/bin/snry-daemon send launch "wps" "onlyoffice-desktopeditors" "libreoffice"
$textEditor = ~/.local/bin/snry-daemon send launch "kate" "gnome-text-editor" "emacs"
$volumeMixer = ~/.local/bin/snry-daemon send launch "pavucontrol-qt" "pavucontrol"
$settingsApp = ~/.local/bin/snry-daemon send launch "XDG_CURRENT_DESKTOP=gnome qs -p ~/.config/quickshell/$qsConfig/settings.qml" "XDG_CURRENT_DESKTOP=gnome systemsettings" "XDG_CURRENT_DESKTOP=gnome gnome-control-center" "XDG_CURRENT_DESKTOP=gnome better-control"
$taskManager = ~/.local/bin/snry-daemon send launch "gnome-system-monitor" "plasma-systemmonitor --page-name Processes" "command -v btop && ghostty -e btop"

# The folder within ~/.config/quickshell containing the config
$qsConfig = ii

# Leave blank like this to load default config. Set to anything to not.
$dontLoadDefaultExecs =
$dontLoadDefaultGeneral =
$dontLoadDefaultRules =
$dontLoadDefaultKeybinds =
