$lock_cmd = hyprctl dispatch global quickshell:lock & pidof qs quickshell hyprlock || hyprlock
# $lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
    on_unlock_cmd = xrandr --output DP-1 --primary
    inhibit_sleep = 3
}

listener {
    # Timeout 110 seconds: Turn off DPMS
    timeout = 110
    on-timeout = hyprctl dispatch dpms off
}

listener {
    # Timeout 120 seconds: Lock session
    timeout = 120
    on-timeout = loginctl lock-session
}

#listener {
#    # Timeout 10 seconds: Turn off DPMS if hyprlock is running
#    timeout = 10
#    on-timeout = pidof qs quickshell hyprlock >/dev/null && hyprctl dispatch dpms off
#}

#listener {
#    timeout = 300 # 5mins
#    on-timeout = loginctl lock-session
#}
#
#listener {
#    timeout = 600 # 10mins
#    on-timeout = hyprctl dispatch dpms off
#    on-resume = hyprctl dispatch dpms on
#}
#
#listener {
#    timeout = 900 # 15mins
#    on-timeout = $suspend_cmd
#}
