package wallpaper

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// TerminalScheme represents the base scheme for terminal colors.
type TerminalScheme struct {
	Dark  map[string]string `json:"dark"`
	Light map[string]string `json:"light"`
}

// LoadTerminalScheme loads the base terminal color scheme from scheme-base.json.
func LoadTerminalScheme(path string) (*TerminalScheme, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read terminal scheme: %w", err)
	}
	var scheme TerminalScheme
	if err := json.Unmarshal(data, &scheme); err != nil {
		return nil, fmt.Errorf("parse terminal scheme: %w", err)
	}
	return &scheme, nil
}

// ColorMap is a string-keyed map of hex color values.
type ColorMap map[string]string

// LoadColorMapFromJSON reads colors.json generated by matugen.
func LoadColorMapFromJSON(path string) (ColorMap, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read colors.json: %w", err)
	}
	var colors ColorMap
	if err := json.Unmarshal(data, &colors); err != nil {
		return nil, fmt.Errorf("parse colors.json: %w", err)
	}
	return colors, nil
}

// GenerateTerminalColors harmonizes terminal base colors against the primary accent color.
func GenerateTerminalColors(
	colors ColorMap,
	scheme *TerminalScheme,
	isDark bool,
	harmony, harmonizeThreshold, termFgBoost float64,
) map[string]string {
	mode := "dark"
	schemeColors := scheme.Dark
	if !isDark {
		mode = "light"
		schemeColors = scheme.Light
	}
	_ = mode

	result := make(map[string]string, len(schemeColors))

	primaryHex := colors["primary"]
	primaryARGB := HexToARGB(primaryHex)

	for name, baseHex := range schemeColors {
		if isMonochromeFromColors(colors) {
			// In monochrome, don't harmonize
			result[name] = baseHex
			continue
		}

		baseARGB := HexToARGB(baseHex)

		var harmonizedARGB uint32
		switch name {
		case "term0": // background
			if termFgBoost > 0 {
				bgARGB := HexToARGB(colors["surface_container_low"])
				harmonizedARGB = BoostChromaTone(bgARGB, 1.2, 0.95)
			} else {
				harmonizedARGB = Harmonize(baseARGB, primaryARGB, harmonizeThreshold, harmony)
			}
		case "term15": // foreground
			if termFgBoost > 0 {
				fgARGB := HexToARGB(colors["on_surface"])
				boostFactor := 1.0 + termFgBoost
				if !isDark {
					boostFactor = 1.0 - termFgBoost
				}
				harmonizedARGB = BoostChromaTone(fgARGB, 3, boostFactor)
			} else {
				harmonizedARGB = Harmonize(baseARGB, primaryARGB, harmonizeThreshold, harmony)
			}
		default:
			harmonizedARGB = Harmonize(baseARGB, primaryARGB, harmonizeThreshold, harmony)
			boostFactor := 1.0 + termFgBoost*1
			if !isDark {
				boostFactor = 1.0 - termFgBoost*1
			}
			harmonizedARGB = BoostChromaTone(harmonizedARGB, 1, boostFactor)
		}

		result[name] = ARGBToHex(harmonizedARGB)
	}

	return result
}

func isMonochromeFromColors(colors ColorMap) bool {
	// Heuristic: if primary and surface are very similar in hue, it's monochrome
	primary := HCTFromARGB(HexToARGB(colors["primary"]))
	surface := HCTFromARGB(HexToARGB(colors["surface"]))
	diff := differenceDegrees(primary.Hue, surface.Hue)
	return diff < 5 && primary.Chroma < 15
}

// GenerateGhosttyConfig writes a valid ghostty theme configuration file.
// Ghostty expects: key = #RRGGBB (no template placeholders).
func GenerateGhosttyConfig(colors ColorMap, termColors map[string]string, isDark bool) string {
	var b strings.Builder

	fmt.Fprintf(&b, "background = %s\n", colors["surface"])
	fmt.Fprintf(&b, "foreground = %s\n", colors["on_surface"])
	fmt.Fprintf(&b, "cursor-color = %s\n", colors["on_surface"])
	fmt.Fprintf(&b, "selection-background = %s\n", colors["on_secondary_container"])
	fmt.Fprintf(&b, "selection-foreground = %s\n", colors["secondary_container"])
	b.WriteString("\n")

	// Standard 16 palette entries
	for i := 0; i <= 15; i++ {
		key := fmt.Sprintf("term%d", i)
		if hex, ok := termColors[key]; ok {
			fmt.Fprintf(&b, "palette = %d=%s\n", i, hex)
		}
	}

	b.WriteString("\n")
	// Extended palette entries matching the original template
	extended := []struct {
		idx  int
		name string
	}{
		{255, "primary"}, {254, "primary_container"}, {253, "secondary"},
		{252, "secondary_container"}, {251, "tertiary"}, {250, "tertiary_container"},
		{249, "error"}, {248, "error_container"},
	}
	for _, e := range extended {
		if hex, ok := colors[e.name]; ok {
			fmt.Fprintf(&b, "palette = %d=%s\n", e.idx, hex)
		}
	}

	b.WriteString("\n")
	// On- container entries
	onEntries := []struct {
		idx  int
		name string
	}{
		{232, "on_primary"}, {233, "on_primary_container"}, {234, "on_secondary"},
		{235, "on_secondary_container"}, {236, "on_tertiary"}, {237, "on_tertiary_container"},
		{238, "on_error"}, {239, "on_error_container"}, {240, "on_primary"},
	}
	for _, e := range onEntries {
		if hex, ok := colors[e.name]; ok {
			fmt.Fprintf(&b, "palette = %d=%s\n", e.idx, hex)
		}
	}

	b.WriteString("\n")
	// Accent entries
	accents := []struct {
		idx  int
		name string
	}{
		{243, "primary"}, {244, "error"}, {245, "outline_variant"},
	}
	for _, e := range accents {
		if hex, ok := colors[e.name]; ok {
			fmt.Fprintf(&b, "palette = %d=%s\n", e.idx, hex)
		}
	}

	return b.String()
}

// GenerateTerminalSequences writes OSC escape sequences for terminal color application.
// These are sent to /dev/pts/* to set colors in running terminals.
func GenerateTerminalSequences(colors ColorMap, termColors map[string]string) string {
	var b strings.Builder

	// Palette entries 0-15
	for i := 0; i <= 15; i++ {
		key := fmt.Sprintf("term%d", i)
		if hex, ok := termColors[key]; ok {
			fmt.Fprintf(&b, "\x1b]4;%d;%s\x1b\\", i, hex)
		}
	}

	// Extended palette entries
	extended := map[int]string{
		232: colors["surface"], // background-like
		255: colors["primary"],
		254: colors["primary_container"],
		253: colors["secondary"],
		252: colors["secondary_container"],
		251: colors["tertiary"],
		250: colors["tertiary_container"],
		249: colors["error"],
		248: colors["error_container"],
	}
	for idx, hex := range extended {
		fmt.Fprintf(&b, "\x1b]4;%d;%s\x1b\\", idx, hex)
	}

	// On- entries
	onEntries := map[int]string{
		232: colors["on_primary"],
		233: colors["on_primary_container"],
		234: colors["on_secondary"],
		235: colors["on_secondary_container"],
		236: colors["on_tertiary"],
		237: colors["on_tertiary_container"],
		238: colors["on_error"],
		239: colors["on_error_container"],
		240: colors["on_primary"],
	}
	for idx, hex := range onEntries {
		fmt.Fprintf(&b, "\x1b]4;%d;%s\x1b\\", idx, hex)
	}

	// Accent entries
	accents := map[int]string{
		243: colors["primary"],
		244: colors["error"],
		245: colors["outline_variant"],
	}
	for idx, hex := range accents {
		fmt.Fprintf(&b, "\x1b]4;%d;%s\x1b\\", idx, hex)
	}

	// Foreground/background
	termFg, fgOk := termColors["term7"]
	termBg, bgOk := termColors["term0"]
	if fgOk {
		fmt.Fprintf(&b, "\x1b]10;%s\x1b\\", termFg) // foreground
	}
	if bgOk {
		fmt.Fprintf(&b, "\x1b]11;[100]%s\x1b\\", termBg)  // background
		fmt.Fprintf(&b, "\x1b]12;%s\x1b\\", termFg)       // cursor
		fmt.Fprintf(&b, "\x1b]13;%s\x1b\\", termFg)       // cursor foreground
		fmt.Fprintf(&b, "\x1b]17;%s\x1b\\", termFg)       // selection fg
		fmt.Fprintf(&b, "\x1b]19;%s\x1b\\", termBg)       // selection bg
		fmt.Fprintf(&b, "\x1b]708;[100]%s\x1b\\", termBg) // bg
	}

	return b.String()
}

func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// ApplyTerminalTheme writes terminal theme files (ghostty config + sequences)
// and optionally sends SIGUSR1 to ghostty processes.
func ApplyTerminalTheme(
	colors ColorMap,
	termColors map[string]string,
	isDark bool,
	genDir string,
) error {
	// Write ghostty theme
	termDir := filepath.Join(genDir, "terminal")
	if err := os.MkdirAll(termDir, 0755); err != nil {
		return fmt.Errorf("create terminal dir: %w", err)
	}

	ghosttyContent := GenerateGhosttyConfig(colors, termColors, isDark)
	if err := os.WriteFile(filepath.Join(termDir, "ghostty-theme.conf"), []byte(ghosttyContent), 0644); err != nil {
		return fmt.Errorf("write ghostty theme: %w", err)
	}

	// Write terminal sequences
	seqContent := GenerateTerminalSequences(colors, termColors)
	if err := os.WriteFile(filepath.Join(termDir, "sequences.txt"), []byte(seqContent), 0644); err != nil {
		return fmt.Errorf("write sequences: %w", err)
	}

	// Signal ghostty to reload
	SignalGhostty()

	// Broadcast sequences to /dev/pts
	BroadcastSequences(filepath.Join(termDir, "sequences.txt"))

	return nil
}
