### This file contains a list of dependencies which were previously explicitly installed that are now installed using meta packages
### Must be one package per line as it needs to be compared against the explicitly installed list from pacman
bc
coreutils
cliphist
cmake
curl
fuzzel
rsync
wget
ripgrep
gjs
xdg-user-dirs
tinyxml2
gtkmm3
gtksourceviewmm
cairomm
xdg-desktop-portal
xdg-desktop-portal-gtk
pavucontrol
wireplumber
libdbusmenu-gtk3
playerctl
gtk-layer-shell
gtk3
gobject-introspection
upower
ydotool
gnome-keyring
gnome-control-center
blueberry
brightnessctl
ddcutil
hypridle-git
wlogout
wl-clipboard
fontconfig
ttf-readex-pro
ttf-jetbrains-mono-nerd
ttf-material-symbols-variable-git
fish
foot
starship
swappy
wf-recorder
grim
tesseract
tesseract-data-eng
slurp
