background ##$term0 #
foreground ##$term7 #
cursor-color ##$term7 #
selection-background ##$onSecondaryContainer #
selection-foreground ##$secondaryContainer #

palette = 0=##$term0 #
palette = 1=##$term1 #
palette = 2=##$term2 #
palette = 3=##$term3 #
palette = 4=##$term4 #
palette = 5=##$term5 #
palette = 6=##$term6 #
palette = 7=##$term7 #
palette = 8=##$term8 #
palette = 9=##$term9 #
palette = 10=##$term10 #
palette = 11=##$term11 #
palette = 12=##$term12 #
palette = 13=##$term13 #
palette = 14=##$term14 #
palette = 15=##$term15 #

palette = 255=##$primary #
palette = 254=##$primaryContainer #
palette = 253=##$secondary #
palette = 252=##$secondaryContainer #
palette = 251=##$tertiary #
palette = 250=##$tertiaryContainer #
palette = 249=##$error #
palette = 248=##$errorContainer #

palette = 232=##$onPrimary #
palette = 233=##$onPrimaryContainer #
palette = 234=##$onSecondary #
palette = 235=##$onSecondaryContainer #
palette = 236=##$onTertiary #
palette = 237=##$onTertiaryContainer #
palette = 238=##$onError #
palette = 239=##$onErrorContainer #
palette = 240=##$onPrimary #

palette = 243=##$primary #
palette = 244=##$error #
palette = 245=##$outlineVariant #
