// Generated by go-wayland-scanner
// https://github.com/rajveermalviya/go-wayland/cmd/go-wayland-scanner
// XML file : /usr/share/wayland-protocols/staging/ext-idle-notify/ext-idle-notify-v1.xml

package protocol

import "github.com/rajveermalviya/go-wayland/wayland/client"

type ExtIdleNotifierV1 struct {
	client.BaseProxy
}

func (i *ExtIdleNotifierV1) Interface() string { return "ext_idle_notifier_v1" }
func (i *ExtIdleNotifierV1) Version() uint32   { return 1 }

func NewExtIdleNotifierV1(ctx *client.Context) *ExtIdleNotifierV1 {
	extIdleNotifierV1 := &ExtIdleNotifierV1{}
	ctx.Register(extIdleNotifierV1)
	return extIdleNotifierV1
}

func (i *ExtIdleNotifierV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0 //nolint:ineffassign
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

func (i *ExtIdleNotifierV1) GetIdleNotification(timeout uint32, seat *client.Seat) (*ExtIdleNotificationV1, error) {
	id := NewExtIdleNotificationV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0 //nolint:ineffassign
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(timeout))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

func (i *ExtIdleNotifierV1) GetInputIdleNotification(timeout uint32, seat *client.Seat) (*ExtIdleNotificationV1, error) {
	id := NewExtIdleNotificationV1(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0 //nolint:ineffassign
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(timeout))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

type ExtIdleNotificationV1 struct {
	client.BaseProxy
	idledHandler   ExtIdleNotificationV1IdledHandlerFunc
	resumedHandler ExtIdleNotificationV1ResumedHandlerFunc
}

func (i *ExtIdleNotificationV1) Interface() string { return "ext_idle_notification_v1" }
func (i *ExtIdleNotificationV1) Version() uint32   { return 1 }

func NewExtIdleNotificationV1(ctx *client.Context) *ExtIdleNotificationV1 {
	extIdleNotificationV1 := &ExtIdleNotificationV1{}
	ctx.Register(extIdleNotificationV1)
	return extIdleNotificationV1
}

func (i *ExtIdleNotificationV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0 //nolint:ineffassign
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ExtIdleNotificationV1IdledEvent struct{}
type ExtIdleNotificationV1IdledHandlerFunc func(ExtIdleNotificationV1IdledEvent)

func (i *ExtIdleNotificationV1) SetIdledHandler(f ExtIdleNotificationV1IdledHandlerFunc) {
	i.idledHandler = f
}

type ExtIdleNotificationV1ResumedEvent struct{}
type ExtIdleNotificationV1ResumedHandlerFunc func(ExtIdleNotificationV1ResumedEvent)

func (i *ExtIdleNotificationV1) SetResumedHandler(f ExtIdleNotificationV1ResumedHandlerFunc) {
	i.resumedHandler = f
}

func (i *ExtIdleNotificationV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.idledHandler == nil {
			return
		}
		var e ExtIdleNotificationV1IdledEvent
		i.idledHandler(e)
	case 1:
		if i.resumedHandler == nil {
			return
		}
		var e ExtIdleNotificationV1ResumedEvent
		i.resumedHandler(e)
	}
}
